-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 22:12:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinemadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinemadb` ;

-- -----------------------------------------------------
-- Schema cinemadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemadb` DEFAULT CHARACTER SET utf8mb4 ;
USE `cinemadb` ;

-- -----------------------------------------------------
-- Table `cinemadb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`users` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`movies` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`movies` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `url_move` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`like` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`like` (
  `like_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`like_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `moveid_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_id_like`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemadb`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_movie_id_like`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinemadb`.`movies` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`watched_movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`watched_movies` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`watched_movies` (
  `watched_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`watched_id`),
  INDEX `moveid_idx` (`movie_id` ASC) VISIBLE,
  INDEX `FK_user_id_watched_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_id_watched`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemadb`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_movie_id_watched`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinemadb`.`movies` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`favourites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`favourites` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`favourites` (
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`favorite_id`),
  INDEX `moveid_idx` (`movie_id` ASC) VISIBLE,
  INDEX `FK_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_id_favourites`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemadb`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_move_id_favourites`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinemadb`.`movies` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`genres` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `namegGenres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinemadb`.`movie_genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinemadb`.`movie_genres` ;

CREATE TABLE IF NOT EXISTS `cinemadb`.`movie_genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`genre_id`, `movie_id`),
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `FKgenre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `cinemadb`.`genres` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKmovie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinemadb`.`movies` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
